backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: assets

publish_mode: editorial_workflow

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "content/home.md"
        fields:
          - {label: "タイトル", name: "title", widget: "string"}
          - {label: "紹介", name: "intro", widget: "text"}
          - {label: "写真", name: "image", widget: "image"}

  - label: "Works"
    name: "works"
    folder: "content/works"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "説明", name: "description", widget: "text"}
      - {label: "Featured Work", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "本文", name: "body", widget: "markdown"}
      - {label: "タグ", name: "tags", widget: "list"}
