backend:
  name: git-gateway
  repo: dowdiness/gatsby-bootcamp

media_folder: static/assets
public_folder: assets

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "content/home.md"
        fields:
          - {label: "タイトル", name: "title", widget: "string"}
          - {label: "紹介", name: "intro", widget: "text"}
          - {label: "写真", name: "image", widget: "image"}
      - label: "Profile Page"
        name: "profile"
        file: "content/profile.md"
        fields:
          - {label: "タイトル", name: "title", widget: "string"}
          - {label: "紹介", name: "intro", widget: "text"}
          - {label: "写真", name: "image", widget: "image"}
      - label: "Contact Page"
        name: "contact"
        file: "content/contact.md"
        fields:
          - {label: "タイトル", name: "title", widget: "string"}
          - {label: "文章", name: "intro", widget: "text"}
          - {label: "お問い合わせ内容例文", name: "example", widget: "text"}

  - label: "Works"
    name: "works"
    folder: "content/works"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "work-post"}
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "url", name: "path", widget: "string"}
      - {label: "説明", name: "description", widget: "text"}
      - {label: "優先記事", name: "featuredwork", widget: "boolean"}
      - {label: "見出し写真", name: "featuredimage", widget: image}
      - {label: "ギャラリー", name: "images", widget: image, allow_multiple: "true", media_library: config: multiple: true}
      - {label: "本文", name: "body", widget: "markdown"}